name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: rl8D1FsuacFKdmF5Uk6agOpG
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./  # Adjust this if your project files are in a subdirectory
          vercel-project-name: APPP3  # Set the project name as defined in Vercel
          scope: darksuntv  # If your project is under a team, set your team ID
